### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by mrudolph-dotsource** [ekomi-ltd/eKomi-integration-magento-2#37]
Hey,

could you add support for PHP 7.4?
Magento 2.4.2 supports PHP 7.4.

br

**Comment by blanioo** [comment]
Hello, any feedback about this? We would like to bump Magento to 2.4.2 as well

**Comment by nauman-coeus** [comment]
Hi 

Hope you are doing well. Thank you for writing to us. Dev team is working on it at the moment and hopefully it will be out in a day or two.

Kind Regards,
Nauman Nasir.

**Comment by QwertyKamil** [comment]
Hi

I see u make update @nauman-coeus, but i still get error
 
```
  [InvalidArgumentException]                                                                          
  Could not find package ekomiltd/ekomiintegration in any version matching your PHP version (7.4.15) 
```

I think it should be 
`"php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0|~7.3.0|~7.3.1|~7.4.0",`
instead
`"php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0|~7.3.0|~7.3.1|~7.4",`
in composer.json

Can u check it?

**Comment by nauman-coeus** [comment]
Hi,

Hope you are doing well. Thanks for pointing it out. Kindly check it out again as we have updated it.

- Regards

**Comment by QwertyKamil** [comment]
Thanks,
 
You updated master, but did't update/create new tag - so i can't get new version by composer

Regards

**Comment by nauman-coeus** [comment]
Hi,
The new release 2.5.4 is made. Try it please

**Comment by QwertyKamil** [comment]
Same error when i try to add it by CLI.

I added package with version in composer.json and then `composer install` and i've getting
`
The requested package ekomiltd/ekomiintegration 2.5.4 exists as ekomiltd/ekomiintegration[1.3.0, 2.5.0, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.1, 2.2.0, 2.1.1, 2.1.0, 2.0.1, 2.0.0] but these are rejected by your constraint
`
so version 2.5.3 and 2.5.4 doesn't exist.

Perhaps this is due to the addition of directories?

https://github.com/ekomi-ltd/eKomi-integration-magento-2/tree/2.5.0
https://github.com/ekomi-ltd/eKomi-integration-magento-2/tree/2.5.3

Kindly check it out again.

**Comment by nauman-coeus** [comment]
Hmm,

Yes you are right i think it needs an additional file to tell the actual dir structure. Wait let me check it out ill write to you when its updated.

**Comment by QwertyKamil** [comment]
OK, thanks for your fast reaction

**Comment by nauman-coeus** [comment]
Hi,

Hope you are doing well.
For now I have reverted the same dir structure as before, however I didnt make new release for it. Can you kindly try to install the same 2.5.4 release again ? If it doesnt work ill push a new release for it :).
Please update me on it

Kind Regards.

**Comment by QwertyKamil** [comment]
Same error, i think new release is needed :)

**Comment by nauman-coeus** [comment]
Hi,
Ok i have uploaded 2.5.6 can you check :)

**Comment by QwertyKamil** [comment]
Yes, it works now :D

Thank you sooo much

**Comment by nauman-coeus** [comment]
Perfect thank you so much bro for letting me know :) :+1:
