### ISSUE TITLE
Commented config

### ISSUE THREAD

**Issue by QwertyKamil** [ekomi-ltd/eKomi-integration-magento-2#48]
Hi,

Can you tell me, why prc config is removed/commented 
https://github.com/ekomi-ltd/eKomi-integration-magento-2/blob/master/etc/adminhtml/system.xml

I need this in my graphQL module to pass this data, and need to change it in admin panel.

I used 2.5.0 version, but it doesn't support php7.4 so after update magento to 2.4.1 I can't use yours package

Can you restore this config in next version?

**Comment by QwertyKamil** [comment]
@nauman-coeus can you help me like whit this issue https://github.com/ekomi-ltd/eKomi-integration-magento-2/issues/37 , please?

**Comment by naumanxds** [comment]
Hi,

Hope you are doing well kamil.
As for the feature we cant bring it back to since it was recently removed and as approved by our supervisors. The feature was removed because it was creating a lot of confusion for the clients. If you still need it we can provide you with an older copy of the plugin and you can install it manually on your system.

Kind Regards,
Nauman Nasir,
Ekomi Ltd.
